Repository AT-12/file-conversion-api-tests, pull requests merged in 2020-11, with the labels that each got.

#14 [develop] JSON Schema Validation Class
  build.gradle
  src/test/java/org/fundacionjala/fc/utils/.gitkeep
  src/test/java/org/fundacionjala/fc/utils/JsonSchemaValidator.java
Labels: changes requested

#21 [develop] Properties reader
  gradle.properties
  src/main/java/org/fundacionjala/fc/config/Environment.java
  src/test/java/org/fundacionjala/fc/unit/tests/EnvironmentTests.java
Labels: changes requested

#30 [develop] Request Manager
  src/main/java/org/fundacionjala/fc/client/AuthenticationUtils.java
  src/main/java/org/fundacionjala/fc/client/RequestManager.java
Labels: changes requested

#16 [develop] Write Test Scenarios ConvertAudio
  src/test/resources/features/convertAudio/audio.feature
Labels: approved

#22 [develop] Write Test Scenarios ExtractMetadata
  src/test/resources/features/extractMetadata/extract.feature
Labels: approved

#34 [develop] Mapper utility class
  src/main/java/org/fundacionjala/fc/utils/Mapper.java
  src/test/java/org/fundacionjala/fc/unit/tests/MapperTest.java
Labels: changes requested

#24 [develop] Write Test Scenarios ExtractText
  src/test/resources/features/convertExtractText/ExtractText.feature
  src/test/resources/templates/image/text.png
Labels: changes requested

#39 [develop] Audio converter test implementation
  src/test/resources/features/convertAudio/audio.feature
Labels: code review
